### ISSUE TITLE
Not working on debian based systems

### ISSUE THREAD

**Issue by ricbir** [Matthewspear/CSTimetableConverter#1]
Just one quick fix: the script uses the command 'open' to open the calendar file. That command is called 'see' on debian-based systems, on which the script returns 'Couldn't get a file descriptor referring to the console'.
Replacing 'open' with 'see' makes it work.

**Comment by matthewspear** [comment]
Thanks, I was expecting this to be a problem - I'll try and add some sort of system specific branching to allow the script to work cross platform!
